### PR TITLE
Implement wasmedge-llmc Rust SDK

### PR DESCRIPTION
**Pull request by junaire**
Related https://github.com/WasmEdge/WasmEdge/issues/3523

### CODE REVIEW

**Comment by junaire** [comment]
hi @hydai, i just got this error when trying to run the example, any ideas about why?
```
❯ ../WasmEdge/build/tools/wasmedge/wasmedge --dir .:. ./example/target/wasm32-wasi/release/example.wasm
[2024-08-20 11:06:18.066] [error] instantiation failed: unknown import, Code: 0x302
[2024-08-20 11:06:18.066] [error]     When linking module: "wasi_llm" , function name: "model_create"
[2024-08-20 11:06:18.066] [error]     At AST node: import description
[2024-08-20 11:06:18.066] [error]     At AST node: import section
[2024-08-20 11:06:18.066] [error]     At AST node: module
```

**Comment by hydai** [comment]
> hi @hydai, i just got this error when trying to run the example, any ideas about why?
> 
> ```
> ❯ ../WasmEdge/build/tools/wasmedge/wasmedge --dir .:. ./example/target/wasm32-wasi/release/example.wasm
> [2024-08-20 11:06:18.066] [error] instantiation failed: unknown import, Code: 0x302
> [2024-08-20 11:06:18.066] [error]     When linking module: "wasi_llm" , function name: "model_create"
> [2024-08-20 11:06:18.066] [error]     At AST node: import description
> [2024-08-20 11:06:18.066] [error]     At AST node: import section
> [2024-08-20 11:06:18.066] [error]     At AST node: module
> ```

Do you put the plugin into the plugin folder? Or use `WASMEDGE_PLUGIN_PATH` to specify the plugin path.

**Comment by hydai** [comment]
I think we should also have a workflow to verify the building process.

**Comment by junaire** [comment]
> > hi @hydai, i just got this error when trying to run the example, any ideas about why?
> > ```
> > ❯ ../WasmEdge/build/tools/wasmedge/wasmedge --dir .:. ./example/target/wasm32-wasi/release/example.wasm
> > [2024-08-20 11:06:18.066] [error] instantiation failed: unknown import, Code: 0x302
> > [2024-08-20 11:06:18.066] [error]     When linking module: "wasi_llm" , function name: "model_create"
> > [2024-08-20 11:06:18.066] [error]     At AST node: import description
> > [2024-08-20 11:06:18.066] [error]     At AST node: import section
> > [2024-08-20 11:06:18.066] [error]     At AST node: module
> > ```
> 
> Do you put the plugin into the plugin folder? Or use `WASMEDGE_PLUGIN_PATH` to specify the plugin path.

thanks, I can confirm it works after setting `WASMEDGE_PLUGIN_PATH`. however, I ran into other problems. so it turns out you cannot use relative path to specify the checkpoint/dataset since it will cause llm.c to incorrectly resolve the path. what's worse is wasm32-wasi has no support for accessing the filesystem, which means trying to get the absolute path of the data directory is also impossible. not sure what's the best solution, wdyt? @hydai 

EDIT: I would like just put these into /tmp directory, that should be fine now.

**Comment by junaire** [comment]
> I think we should also have a workflow to verify the building process.

can you enable the workflow?

**Comment by hydai** [comment]
> thanks, I can confirm it works after setting `WASMEDGE_PLUGIN_PATH`. however, I ran into other problems. so it turns out you cannot use relative path to specify the checkpoint/dataset since it will cause llm.c to incorrectly resolve the path. what's worse is wasm32-wasi has no support for accessing the filesystem, which means trying to get the absolute path of the data directory is also impossible. not sure what's the best solution, wdyt? @hydai
> 
> EDIT: I would like just put these into /tmp directory, that should be fine now.

First of all, you can check the `wasi-nn` and `nn-preload` options, which will allow you to access the local files. We are going to implement the VFS for the plugin systems. Then, it will be easier to access the local files when users grant permission with `--dir`.



> can you enable the workflow?

I already enabled it. However, it's weird that your workflows are not triggered.

**Comment by junaire** [comment]
> I already enabled it. However, it's weird that your workflows are not triggered.

well, no clue then since i don't believe my code has anything wrong. githubstatus.com also shows everything is working normally. can you plz double-check the settings that are related to this?

**Comment by hydai** [comment]
CleanShot 2024-08-21 at 13 16 00
CleanShot 2024-08-21 at 13 16 27
Here you go ;-)

**Comment by hydai** [comment]
Hi @junaire 
I just created and merged a workflow. It seems to be working. Could you please try again and move your changes on it?

**Comment by junaire** [comment]
> Hi @junaire I just created and merged a workflow. It seems to be working. Could you please try again and move your changes on it?

thanks, I think that works, can you approve the workflow?

**Comment by junaire** [comment]
can you take a look at https://github.com/WasmEdge/llm.c/pull/4?

**Comment by hydai** [comment]
> can you take a look at [WasmEdge/llm.c#4](https://github.com/WasmEdge/llm.c/pull/4)?

Done.

**Comment by junaire** [comment]
can you approve the workflow, again? @hydai

**Comment by hydai** [comment]
> can you approve the workflow, again? @hydai

Sure. Maybe you can create a PR to your own forked repo. It should also trigger the CI, so you don't have to wait for me to approve the workflow execution.

**Comment by junaire** [comment]
> > can you approve the workflow, again? @hydai
> 
> Sure. Maybe you can create a PR to your own forked repo. It should also trigger the CI, so you don't have to wait for me to approve the workflow execution.

well you can change the configuration in the settings so both of our lives will be easier
image

**Comment by hydai** [comment]
We cannot do so for security reasons. It will allow users to execute non-approved workflows on our self-hosted runners.

**Review by hydai — APPROVED** [review]

**Pull request merged**
